import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import Style from "@/styles/Home.module.css";
import { useEffect, useState } from "react";
import axios from "axios";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [price, setPrice] = useState(0);
  const [days, setDays] = useState(1);
  const [priceForDays, setPriceForDays] = useState(1);

  useEffect(() => {
    axios.get("/api/hello").then((res: any) => {
      console.log(res.data.data);
      setPrice(res.data.data);
    });
  }, []);
  const handelChange = (e: any) => {
    const valueDays = e.target.value;
    setDays(valueDays);
    setPriceForDays(price * valueDays);
  };
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={Style.main}>
        <h3>el precio de Helium Token ahroa es {price} $</h3> <br />
        <p>
          cuanto vas a ganar al Mes si el precio de Helium es {price} $ , vas a
          ganar {price * 30} $
        </p>
        <div className={Style.input_container}>
          <p>entrar cunatos dias quieres abajo</p>
          <input
            type="number"
            min="0"
            onChange={handelChange}
            className={Style.input}
          />{" "}
          <br />
        </div>
        <p>
          Dias : {days} <br />
          Vas ganar : {priceForDays} $
        </p>
      </main>
    </>
  );
}
